[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = []
  external_node_modules = ["node-fetch"]

[[redirects]]
  from = "/api/check_number"
  to = "/.netlify/functions/api-check-number"
  status = 200
  force = true

[[redirects]]
  from = "/api/check_number_no_captcha"
  to = "/.netlify/functions/api-check-number"
  status = 200
  force = true

[[redirects]]
  from = "/api/create-payment"
  to = "/.netlify/functions/api-create-payment"
  status = 200
  force = true

[[redirects]]
  from = "/api/store-phone"
  to = "/.netlify/functions/api-store-phone"
  status = 200
  force = true

[[redirects]]
  from = "/api/topup"
  to = "/.netlify/functions/api-topup"
  status = 200
  force = true

[[redirects]]
  from = "/payment-success"
  to = "/.netlify/functions/payment-success"
  status = 200
  force = true

[[redirects]]
  from = "/payment-cancel"
  to = "/.netlify/functions/payment-cancel"
  status = 200
  force = true

[[redirects]]
  from = "/api/retry-telegram"
  to = "/.netlify/functions/api-retry-telegram"
  status = 200
  force = true

[[redirects]]
  from = "/store-backend/*"
  to = "/.netlify/functions/store-backend"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

# Scheduled function for retrying Telegram messages
[functions.scheduled-task]
  schedule = "@hourly"